services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - robot_network
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: influxdb_v2
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=diploma2024
      - DOCKER_INFLUXDB_INIT_ORG=diploma_org
      - DOCKER_INFLUXDB_INIT_BUCKET=robot_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    ports:
      - "8086:8086"
    networks:
      - robot_network
    restart: unless-stopped

  telegraf:
    build: ./telegraf
    container_name: telegraf_agent
    networks:
      - robot_network
    depends_on:
      - mqtt
      - influxdb
    restart: unless-stopped

  grafana_dashboard:
    image: grafana/grafana:9.5.0
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana  # ← ДОБАВЬ ЭТУ СТРОЧКУ
    networks:
      - robot_network
    depends_on:
      - influxdb

networks:
  robot_network:

volumes:
  influxdb_data:
  grafana_data: